### ISSUE TITLE
Request for a release

### ISSUE THREAD

**Issue by callkalpa** [sugarlabs/pukllanapac#6]
@quozl, @walterbender  Is it possible to do a release with porting to gtk3 in so that the latest version can be packaged for Fedora?

**Comment by walterbender** [comment]
I just made a PR with a new version number (and an updated repository field).

**Comment by quozl** [comment]
Merged.  As I understand it, next steps are `python setup.py dist_xo`, bundle upload to ASLO, bundle upload to downloads.sugarlabs.org.  I've no access for the last two, but if someone can get me access, that would be grand.

**Comment by walterbender** [comment]
I'll update ASLO and download.sl.o

**Comment by quozl** [comment]
Yay.
